# Generated by Django 5.2.5 on 2025-08-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsEvent',
            new_name='Incident',
        ),
        migrations.RenameModel(
            old_name='NewsSource',
            new_name='Source',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('published', models.DateTimeField()),
                ('summary', models.TextField(blank=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.incident')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsArticle',
        ),
    ]
